language: python
python:
  - 2.7.15

before_install:
  - sudo apt-get install -y zip
  - sudo apt-get install unzip
  - wget https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip
  - unzip terraform_0.12.7_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - terraform --version 
install:
#   - sudo pip install -r requirements.txt

script: 
#   - ./ecomap/bin/run_all_unittests.sh
  - zip -r test_ecomap.zip *
  - export AWS_ACCESS_KEY_ID="secret"
  - export AWS_SECRET_ACCESS_KEY="secret"
  - terraform init
  - terraform plan
  - terraform apply -auto-approve
  
# deploy:
#   provider: s3
#   access_key_id: "YOUR AWS ACCESS KEY"
#   secret_access_key: "YOUR AWS SECRET KEY"
#   bucket: "S3 Bucket"

# deploy:
# #   skip_cleanup: true
#   provider: s3
#   access_key_id: "$access_key_id"
#   secret_access_key: "$secret_access_key"
# #   region: "us-east-2"
#   bucket_name: "ecomap-new-version"
#   zip_file: test_ecomap.zip
# #   on: 
# # branch: master
#goggoog

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $access_key_id
  secret_access_key:
    secure: "$secret_access_key"
  region: "us-east-2"  
  app: "ecomap"
  env: "Ecomap-env"
  bucket_name: "ecomap-new-version"
  #local_dir: eb
  zip_file: test_ecomap.zip
  on:
    branch: master
